config/routes.rb
Gallery::Application.routes.draw do
  resources :dibgalleries
  root to: 'dibgalleries#index'
  match '/dispall', to: 'dibgalleries#dispall'
  match '/layoutdispall', to: 'layouts#dispall'

  










end

app/models/dibgallery.rb
class Dibgallery < ActiveRecord::Base
  validates :title, :presence => true
	has_attached_file :photo1, :styles => { :thumb => "75x75>", :small => "150x150>" }
	has_attached_file :photo2, :styles => { :thumb => "75x75>", :small => "150x150>" }
	has_attached_file :photo3, :styles => { :thumb => "75x75>", :small => "150x150>" }
	has_attached_file :photo4, :styles => { :thumb => "75x75>", :small => "150x150>" }
	has_attached_file :photo5, :styles => { :thumb => "75x75>", :small => "150x150>" }
	has_attached_file :photo6, :styles => { :thumb => "75x75>", :small => "150x150>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dibgalleries_controller.rb
class DibgalleriesController < ApplicationController
  # GET /dibgalleries
  # GET /dibgalleries.json
  def index
    @dibgalleries = Dibgallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dibgalleries }
    end
  end

  # GET /dibgalleries/1
  # GET /dibgalleries/1.json
  def show
    @dibgallery = Dibgallery.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dibgallery }
    end
  end
  
  def dispall
    @dibgalleries = Dibgallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dibgalleries }
    end
  end

  # GET /dibgalleries/new
  # GET /dibgalleries/new.json
  def new
    @dibgallery = Dibgallery.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dibgallery }
    end
  end

  # GET /dibgalleries/1/edit
  def edit
    @dibgallery = Dibgallery.find(params[:id])
  end

  # POST /dibgalleries
  # POST /dibgalleries.json
  def create
    @dibgallery = Dibgallery.new(params[:dibgallery])

    respond_to do |format|
      if @dibgallery.save
        format.html { redirect_to @dibgallery, notice: 'Dibgallery was successfully created.' }
        format.json { render json: @dibgallery, status: :created, location: @dibgallery }
      else
        format.html { render action: "new" }
        format.json { render json: @dibgallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dibgalleries/1
  # PUT /dibgalleries/1.json
  def update
    @dibgallery = Dibgallery.find(params[:id])

    respond_to do |format|
      if @dibgallery.update_attributes(params[:dibgallery])
        format.html { redirect_to @dibgallery, notice: 'Dibgallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dibgallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dibgalleries/1
  # DELETE /dibgalleries/1.json
  def destroy
    @dibgallery = Dibgallery.find(params[:id])
    @dibgallery.destroy

    respond_to do |format|
      format.html { redirect_to dibgalleries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dibgalleries_helper.rb
module DibgalleriesHelper
end

app/views/dibgalleries/_form.html.erb
<%= form_for(@dibgallery, :html => { :multipart => true }) do |f| %>
  <% if @dibgallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dibgallery.errors.count, "error") %> prohibited this dibgallery from being saved:</h2>

      <ul>
      <% @dibgallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"gallery title" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :"gallery description" %><br />
    <%= f.text_area :description, :size => "30x10" %>
  </div>
  <div class="field">
    <%= f.label :"gallery photo" %><br />
    <%= f.file_field :photo1 %>
  </div>
    <div class="field">
    <%= f.label :"gallery photo" %><br />
    <%= f.file_field :photo2 %>
  </div>
    <div class="field">
    <%= f.label :"gallery photo" %><br />
    <%= f.file_field :photo3 %>
  </div>
    <div class="field">
    <%= f.label :"gallery photo" %><br />
    <%= f.file_field :photo4 %>
  </div>
    <div class="field">
    <%= f.label :"gallery photo" %><br />
    <%= f.file_field :photo5 %>
  </div>
    <div class="field">
    <%= f.label :"gallery photo" %><br />
    <%= f.file_field :photo6 %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit'%>
  </div>
<% end %>

app/views/dibgalleries/backup/bkp_28thApril2012_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @dibgallery.title %>
</p>

<p>
  <b>Description:</b>
  <%= @dibgallery.description %>
</p>

<p>
  <b>Photo:</b>
  <a rel="example_group" href="<%= @dibgallery.photo1.url(:original) %>" class="fancybox"><%= image_tag @dibgallery.photo1.url(:small) %></a>
</p>

<p>
  <b>Photo:</b>
  <a rel="example_group" href="<%= @dibgallery.photo2.url(:original) %>" class="fancybox"><%= image_tag @dibgallery.photo2.url(:small) %></a>
</p>

<p>
  <b>Photo:</b>
  <a rel="example_group" href="<%= @dibgallery.photo3.url(:original) %>" class="fancybox"><%= image_tag @dibgallery.photo3.url(:small) %></a>
</p>

<p>
  <b>Photo:</b>
  <a rel="example_group" href="<%= @dibgallery.photo4.url(:original) %>" class="fancybox"><%= image_tag @dibgallery.photo4.url(:small) %></a>
</p>

<p>
  <b>Photo:</b>
  <a rel="example_group" href="<%= @dibgallery.photo5.url(:original) %>" class="fancybox"><%= image_tag @dibgallery.photo5.url(:small) %></a>
</p>

<p>
  <b>Photo:</b>
  <a rel="example_group" href="<%= @dibgallery.photo6.url(:original) %>" class="fancybox"><%= image_tag @dibgallery.photo6.url(:small) %></a>
</p>
<%= link_to 'Edit', edit_dibgallery_path(@dibgallery) %> |
<%= link_to 'Back', dibgalleries_path %>

app/views/dibgalleries/dispall.html.erb
<% @dibgalleries.each do |dibgallery| %>
  <tr>
    <td><%= dibgallery.title %></td>
    <td><%= dibgallery.description %></td>
    <td><%= image_tag dibgallery.photo1.url(:small) %></td>
    <td><%= image_tag dibgallery.photo2.url(:small) %></td>
    <td><%= image_tag dibgallery.photo3.url(:small) %></td>
    <td><%= image_tag dibgallery.photo4.url(:small) %></td>
    <td><%= image_tag dibgallery.photo5.url(:small) %></td>
    <td><%= image_tag dibgallery.photo6.url(:small) %></td>
    <td><%= link_to 'Show', dibgallery %></td>
    <td><%= link_to 'Edit', edit_dibgallery_path(dibgallery) %></td>
    <td><%= link_to 'Destroy', dibgallery, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>

app/views/dibgalleries/edit.html.erb
<h1>Editing dibgallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @dibgallery %> |
<%= link_to 'Back', dibgalleries_path %>

app/views/dibgalleries/index.html.erb
<h1>Welcome</h1>

<p>Far far away, behind the word mountains, far
from the countries Vokalia and Consonantia,
there live the blind texts. Separated they live in
Bookmarksgrove right at the coast of the
Semantics, a large language ocean.</p>

<p>A small river named Duden flows by their place
and supplies it with the necessary regelialia. It is
a paradisematic country, in which roasted parts
of sentences fly into your mouth.<p>

<p>Even the all-powerful Pointing has no control
about the blind texts it is an almost
unorthographic life One day however a small line
of blind text by the name of Lorem Ipsum decided
to leave for the far World of Grammar. The Big
Oxmox advised her not to do so, because there
were thousands of bad Commas.</p>
<br />

<%= link_to 'Create a Gallery', new_dibgallery_path %>


app/views/dibgalleries/new.html.erb
<h1>New Gallery</h1>

<p>Far far away, behind the word mountains, far
from the countries Vokalia and Consonantia,
there live the blind texts. Separated they live in
Bookmarksgrove right at the coast of the
Semantics, a large language ocean.</p>

<%= render 'form' %>

<%= link_to 'Back', dibgalleries_path %>

app/views/dibgalleries/show.html.erb
<table border="0">
	<tr>
		<td colspan="3" align="center"><p id="notice"><%= notice %></p></td>
	</tr>
	<tr>
		<td><b>Title:</b></td>
		<td colspan="2"><%= @dibgallery.title %></td>
	</tr>
	<tr>
		<td><b>Description:</b></td>
		<td colspan="2"><%= @dibgallery.description %></td>
	</tr>
	<tr>
		<td><a rel="example_group" href="<%= @dibgallery.photo1.url(:original) %>" class="fancybox"><%= (image_tag @dibgallery.photo1.url(:thumb), :border => "0") %></a></td>
		<td><a rel="example_group" href="<%= @dibgallery.photo2.url(:original) %>" class="fancybox"><%= (image_tag @dibgallery.photo2.url(:thumb), :border => "0") %></a></td>
		<td><a rel="example_group" href="<%= @dibgallery.photo3.url(:original) %>" class="fancybox"><%= (image_tag @dibgallery.photo3.url(:thumb), :border => "0") %></a></td>
	</tr>
	<tr>
		<td><a rel="example_group" href="<%= @dibgallery.photo4.url(:original) %>" class="fancybox"><%= (image_tag @dibgallery.photo4.url(:thumb), :border => "0") %></a></td>
		<td><a rel="example_group" href="<%= @dibgallery.photo5.url(:original) %>" class="fancybox"><%= (image_tag @dibgallery.photo5.url(:thumb), :border => "0") %></a></td>
		<td><a rel="example_group" href="<%= @dibgallery.photo6.url(:original) %>" class="fancybox"><%= (image_tag @dibgallery.photo6.url(:thumb), :border => "0") %></a></td>
	</tr>
	<tr>
		<td colspan="3" align="center"><%= link_to 'Edit', edit_dibgallery_path(@dibgallery) %> | <%= link_to 'Back', dibgalleries_path %></td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/dispall.html.erb
<% @dibgalleries.each do |dibgallery| %>
  <tr>
    <td><%= dibgallery.title %></td>
    <td><%= dibgallery.description %></td>
    <td><%= image_tag dibgallery.photo1.url(:small) %></td>
    <td><%= image_tag dibgallery.photo2.url(:small) %></td>
    <td><%= image_tag dibgallery.photo3.url(:small) %></td>
    <td><%= image_tag dibgallery.photo4.url(:small) %></td>
    <td><%= image_tag dibgallery.photo5.url(:small) %></td>
    <td><%= image_tag dibgallery.photo6.url(:small) %></td>
    <td><%= link_to 'Show', dibgallery %></td>
    <td><%= link_to 'Edit', edit_dibgallery_path(dibgallery) %></td>
    <td><%= link_to 'Destroy', dibgallery, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>